[package]
name = "satellite"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.3"
ic-cdk = "0.6.8"
ic-cdk-macros = "0.6.8"
serde = "1.0.145"
serde_bytes = "0.11.7"
serde_cbor = "0.11.2"
regex = "1.7.0"
ic-certified-map = "0.3.1"
sha2 = "0.10.6"
base64 = "0.13.1"
url = "2.3.1"
shared = { path = "../shared" }
