name: Release

on:
  release:
    types: [released]

jobs:
  #####################
  # The docker builds #
  #####################

  # The image shared by all builds, containing pre-built rust deps
  docker-build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update

      # We use buildx and its GitHub Actions caching support `type=gha`. For
      # more information, see
      # https://github.com/docker/build-push-action/issues/539
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build base Docker image
        uses: docker/build-push-action@v3
        with:
          file: admin/Dockerfile
          cache-from: type=gha,scope=cached-stage
          cache-to: type=gha,scope=cached-stage,mode=max
          outputs: type=cacheonly
          target: deps

  docker-build:
    runs-on: ubuntu-latest
    needs: docker-build-base
    strategy:
      matrix:
        include:
          - name: console.wasm
            target: scratch_console

          - name: mission_control.wasm
            target: scratch_mission_control

          - name: observatory.wasm
            target: scratch_observatory

          - name: satellite.wasm
            target: scratch_satellite

    steps:
      - uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.name }}
        uses: docker/build-push-action@v3
        with:
          file: admin/Dockerfile
          cache-from: type=gha,scope=cached-stage
          # Exports the artefacts from the final stage
          outputs: ./out
          target: ${{ matrix.target }}

      - run: sha256sum out/${{ matrix.name }}

      - run: mv out/${{ matrix.name }} ${{ matrix.name }}

      - name: 'Upload ${{ matrix.name }}'
        uses: actions/upload-artifact@v3
        with:
          # name is the name used to display and retrieve the artifact
          name: ${{ matrix.name }}
          # path is the name used as the file to upload and the name of the
          # downloaded file
          path: ./${{ matrix.name }}

  metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build metadata
        run: bash ./docker/metadata
        env:
          CANISTERS: console,mission_control,observatory,satellite

      - name: Upload metadata
        uses: actions/upload-artifact@v3
        with:
          # name is the name used to display and retrieve the artifact
          name: metadata.json
          # path is the name used as the file to upload and the name of the
          # downloaded file
          path: ./metadata.json

  release:
    runs-on: ubuntu-latest
    needs: ['docker-build', 'metadata']
    steps:
      - uses: actions/checkout@v3

      - name: Download console.wasm
        uses: actions/download-artifact@v3
        with:
          name: console.wasm
      - name: Download mission_control.wasm
        uses: actions/download-artifact@v3
        with:
          name: mission_control.wasm
      - name: Download observatory.wasm
        uses: actions/download-artifact@v3
        with:
          name: observatory.wasm
      - name: Download satellite.wasm
        uses: actions/download-artifact@v3
        with:
          name: satellite.wasm
      - name: Download metadata.json
        uses: actions/download-artifact@v3
        with:
          name: metadata.json

      - name: Prepare canisters
        run: bash ./docker/prepare
        env:
          CANISTERS: console,mission_control,observatory,satellite

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./console*.wasm
            ./mission_control*.wasm
            ./observatory*.wasm
            ./satellite*.wasm
            ./metadata.json
